/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CaliperApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "CaliperEventArchive": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CaliperEventStream": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "CaliperEvents": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CaliperSensors": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CaliperWebhooks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}